print("This is a python code for homework6-2: Least Square Method and Factorization")
import numpy as np
from scipy.linalg import lu
from scipy import linalg
a = np.array([(1, 9, 1, 9), (8, 1, 0, 1), (1, 4, 5, 1), (4, 1, 1, 4), (5, 1, 4, 1), (9, 1, 9, 8)])
b = np.array([1, 9, 1, 9, 8, 1])
aT = np.transpose(a)
C = aT.dot(a)
CI = np.linalg.pinv(C)
CII = CI.dot(aT)
CIII = CII.dot(b)
U, s, V = linalg.svd(a)
p, l, u = lu(a)
print("****************************** Matrix Setup ******************************")
print("The 4*4 matrix B is:\n", a)
print("************************** Least Square Method ***************************")
print("The least square answer is:\n", CIII)
print("*************************** SVD Factorization ****************************")
print("The U of SVD is:\n", U)
print("The s of SVD is:\n", s)
print("The V of SVD is:\n", V)
s_matrix = np.zeros((6, 4))
s_matrix[:4, :4] = np.diag(s)
VT = np.transpose(V)
UT = np.transpose(U)
print("The verify Avi of SVD is:\nAv1:", a.dot(V[0]))
print("sU1:", UT[0]*s[0])
print("Av2:", a.dot(V[1]))
print("sU2:", UT[1]*s[1])
print("Av3:", a.dot(V[2]))
print("sU3:", UT[2]*s[2])
print("Av4:", a.dot(V[3]))
print("sU4:", UT[3]*s[3])
print("The verify ATui of SVD is:\nATu1:", aT.dot(UT[0]))
print("sV1:", V[0]*s[0])
print("ATu2:", aT.dot(UT[1]))
print("sV2:", V[1]*s[1])
print("ATu3:", aT.dot(UT[2]))
print("sV3:", V[2]*s[2])
print("ATu4:", aT.dot(UT[3]))
print("sV4:", V[3]*s[3])
print("ATu5:", aT.dot(UT[4]))
print("ATu6:", aT.dot(UT[5]))
print("**************************** LU Factorization ****************************")
print("The P of LU is:\n", p)
print("The L of LU is:\n", l)
print("The U of LU is:\n", u)
