print("This is a python code for homework6-1: Calculate of Matrix")
import numpy as np
a = np.array([(1, 9, 1, 9), (8, 1, 0, 1), (1, 4, 5, 1), (4, 0, 0, 1)])
b = np.array([1, 9, 1, 9])
aT = np.transpose(a)
aI = np.linalg.pinv(a)
c = np.linalg.eig(a)
x = aI.dot(b)
print("The 4*4 matrix A is:\n", a)
print("The 4 array b is:\n", b)
print("The answer X of equation AX = b is:\n", x)
print("The transpose of A is:\n", aT)
print("The det(A) is:\n", np.linalg.det(a))
print("The rank(A) is:\n", np.linalg.matrix_rank(a))
print("The Inverse of A is:\n", aI)
print("The Eigenvalues of A are:\n", c[0])
print("The Eigenvectors of A are:\n", c[1])
